/**
 * 관리자 - 글 관리 화면 전용 편집성 콘텐츠.
 *
 * 데이터 타입과 무관한 문자열 상수만 export한다.
 */
export const adminContent = {
  eyebrow: 'Baaaam 운영 공간',
  title: '콘텐츠 관리',
  description: '작성자는 학습 글을 만들고, 관리자는 콘텐츠와 회원 권한을 함께 관리해요.',
  loading: '불러오는 중이에요...',
  session: {
    activeSuffix: '님으로 관리 중',
    signOut: '로그아웃',
    signOutError: '로그아웃에 실패했어요. 잠시 후 다시 시도해주세요.',
  },
  tabsAriaLabel: '관리 메뉴',
  tabs: {
    posts: '글 관리',
    comments: '댓글 관리',
    roles: '권한 관리',
  },
  accessDenied: {
    badge: '일반 회원',
    title: '작성자 권한이 필요해요',
    description: '현재 계정은 글을 읽고 댓글을 남길 수 있어요. 글 작성 권한은 관리자에게 요청해주세요.',
    homeCta: '홈으로 돌아가기',
  },
  roleManager: {
    title: '회원 권한',
    description: '일반 회원을 작성자로 지정하거나 관리자 권한을 부여할 수 있어요.',
    loading: '회원 목록을 불러오는 중이에요...',
    empty: '등록된 회원이 없어요.',
    tableCaption: '회원 권한 목록',
    name: '이름',
    email: '이메일',
    role: '권한',
    selfLabel: '내 계정',
    savedToast: '회원 권한을 변경했어요',
    saveError: '권한 변경에 실패했어요. 잠시 후 다시 시도해주세요.',
    selfHelp: '현재 로그인한 관리자 계정의 권한은 여기서 변경할 수 없어요.',
  },
  loginForm: {
    eyebrow: '운영진 로그인',
    description: '이메일과 비밀번호로 로그인해주세요.',
    emailLabel: '이메일',
    emailPlaceholder: 'name@baaaam.example',
    passwordLabel: '비밀번호',
    passwordPlaceholder: '비밀번호를 입력해주세요',
    submitCta: '로그인',
    submitting: '로그인하는 중...',
    errorFallback: '로그인에 실패했어요. 이메일과 비밀번호를 확인해주세요.',
    switchToSignupPrompt: '아직 계정이 없으신가요?',
    switchToSignupCta: '운영진 가입 신청',
    validation: {
      email: '이메일을 입력해주세요.',
      password: '비밀번호를 입력해주세요.',
    },
  },
  signupForm: {
    eyebrow: '운영진 가입 신청',
    description: '작성자·댓글 관리자로 활동할 운영진 계정을 만들어요.',
    loadingConfig: '가입 조건을 확인하는 중이에요...',
    nameLabel: '이름',
    namePlaceholder: '이름을 입력해주세요',
    emailLabel: '이메일 (로그인 아이디)',
    emailPlaceholder: 'name@baaaam.example',
    passwordLabel: '비밀번호',
    passwordPlaceholder: '8자 이상 입력해주세요',
    phoneLabel: '연락처',
    phonePlaceholder: '010-1234-5678',
    emailCodeSectionTitle: '이메일 인증',
    emailCodeDescription: '가입에는 이메일 인증이 필요해요. 인증코드를 받아 확인해주세요.',
    sendCodeCta: '인증코드 전송',
    sendCodeRetryCta: '다시 보내기',
    codeSentHelp: '인증코드를 보냈어요. 메일함을 확인해주세요.',
    codeInputLabel: '인증코드',
    codeInputPlaceholder: '인증코드 6자리',
    verifyCodeCta: '인증 확인',
    codeVerifiedHelp: '이메일 인증을 완료했어요.',
    termsSectionTitle: '이용약관',
    privacySectionTitle: '개인정보 처리방침',
    termsAgreeLabel: '이용약관에 동의해요',
    privacyAgreeLabel: '개인정보 처리방침에 동의해요',
    submitCta: '가입 신청',
    submitting: '신청하는 중...',
    backToLoginCta: '로그인으로 돌아가기',
    errorFallback: '가입 신청에 실패했어요. 입력값을 확인하고 다시 시도해주세요.',
    successPendingTitle: '가입 신청이 접수됐어요',
    successPendingDescription: '운영진 승인 후 로그인할 수 있어요. 승인되면 다시 로그인해주세요.',
    successActiveTitle: '가입이 완료됐어요',
    successActiveDescription: '이제 이메일과 비밀번호로 로그인할 수 있어요.',
    validation: {
      name: '이름을 입력해주세요.',
      email: '이메일을 입력해주세요.',
      password: '비밀번호를 8자 이상 입력해주세요.',
      phone: '연락처를 입력해주세요.',
      code: '인증코드를 입력해주세요.',
      emailNotVerified: '이메일 인증을 먼저 완료해주세요.',
      termsAgreed: '이용약관에 동의해주세요.',
      privacyAgreed: '개인정보 처리방침에 동의해주세요.',
    },
  },
  postManager: {
    listTitle: '전체 글',
    newPostCta: '새 글 작성',
    editCta: '수정',
    loading: '글 목록을 불러오는 중이에요...',
    empty: '아직 작성된 글이 없어요.',
    tableCaption: '전체 글 목록',
    tableHeaders: {
      title: '제목',
      category: '카테고리',
      author: '작성자',
      recommended: '추천',
      actions: '관리',
    },
    recommendedToggleLabel: '추천 글로 지정',
    createdToast: '새 글을 등록했어요',
    updatedToast: '글을 수정했어요',
  },
  postForm: {
    createTitle: '새 글 작성',
    editTitle: '글 수정',
    titleLabel: '제목',
    categoryLabel: '카테고리',
    categoryPlaceholder: '카테고리를 선택하세요',
    contentLabel: '본문 내용',
    imageLabel: '대표 이미지 키워드',
    imageHelp: '완성된 이미지 주소가 아니라 검색용 짧은 키워드예요 (예: baaaam-math-fractions)',
    imagePlaceholder: 'baaaam-math-fractions',
    videoLabel: '영상 임베드 URL (선택)',
    videoPlaceholder: 'https://www.youtube-nocookie.com/embed/영상ID',
    authorLabel: '작성자',
    cancel: '취소',
    submitCreate: '작성 완료',
    submitUpdate: '수정 완료',
    submitting: '저장하는 중...',
    errorInline: '저장에 실패했어요. 잠시 후 다시 시도해주세요.',
    validation: {
      title: '제목을 입력해주세요.',
      categoryId: '카테고리를 선택해주세요.',
      content: '본문 내용을 입력해주세요.',
      imageUrl: '대표 이미지 키워드를 입력해주세요.',
    },
  },
  commentManager: {
    unansweredTitle: '미답변 질문',
    unansweredEmpty: '아직 답변하지 않은 질문이 없어요.',
    replyPlaceholder: '답변을 입력해주세요',
    replySubmit: '답변 등록',
    replySubmitting: '등록하는 중...',
    replyValidation: '답변 내용을 입력해주세요.',
    replySuccessToast: '답변이 등록되었어요',
    allCommentsTitle: '전체 댓글',
    allCommentsEmpty: '등록된 댓글이 없어요.',
    loading: '댓글을 불러오는 중이에요...',
    questionBadge: '질문',
    deleteCta: '삭제',
    deleteDialogTitle: '이 댓글을 삭제할까요?',
    deleteDialogDescription: '삭제하면 되돌릴 수 없어요. 신중하게 결정해주세요.',
    deleteDialogCancel: '취소',
    deleteDialogConfirm: '삭제',
    deleteSuccessToast: '댓글을 삭제했어요',
  },
}
