/**
 * 글 상세 화면 전용 편집성 콘텐츠.
 *
 * `Post`/`Comment` 데이터 타입과 무관한 문자열 상수만 export한다.
 */
export const postContent = {
  detailLoading: '글을 불러오는 중이에요...',
  notFound: {
    title: '요청하신 글을 찾을 수 없어요',
    description: '주소가 바뀌었거나 삭제된 글일 수 있어요. 홈에서 다른 글을 찾아보세요.',
    homeLink: '홈으로 돌아가기',
  },
  backToCategorySuffix: '목록으로 돌아가기',
  comments: {
    eyebrow: '함께 나누는 이야기',
    title: '댓글',
    countSuffix: '개의 댓글',
    filteredCountSuffix: '개 표시 중',
    refreshLabel: '댓글 새로고침',
    mineLabel: '내 댓글',
    mineBadge: '내 댓글',
    replyBadge: '답글',
    inputLabel: '댓글 내용',
    inputPlaceholder: '댓글을 입력해주세요',
    submit: '등록',
    submitting: '등록 중',
    validation: '댓글 내용을 입력해주세요.',
    createError: '댓글을 등록하지 못했어요. 잠시 후 다시 시도해주세요.',
    createSuccessTitle: '댓글을 등록했어요',
    createSuccessDescription: '작성한 댓글이 바로 목록에 반영됩니다.',
    loginTitle: '로그인하고 댓글을 남겨보세요',
    loginDescription: '궁금한 점이나 글에 대한 생각을 자유롭게 나눌 수 있어요.',
    loginCta: '로그인하기',
    sortLabel: '댓글 정렬',
    latestSort: '최신순',
    oldestSort: '오래된순',
    loading: '댓글을 불러오는 중이에요...',
    loadError: '댓글을 불러오지 못했어요. 잠시 후 새로고침 해주세요.',
    retry: '다시 불러오기',
    empty: '등록된 댓글이 없습니다.',
    mineEmpty: '아직 작성한 댓글이 없습니다.',
    questionBadge: '질문',
    deleteLabel: '댓글 삭제',
    deleteDialogTitle: '댓글을 삭제할까요?',
    deleteDialogDescription: '삭제한 댓글은 다시 복구할 수 없습니다.',
    cancel: '취소',
    deleteConfirm: '삭제',
    deleteSuccessTitle: '댓글을 삭제했어요',
    deleteSuccessDescription: '댓글 목록에서 삭제되었습니다.',
  },
  question: {
    eyebrow: '궁금한 점이 있나요?',
    title: '질문 남기기',
    description: '이름과 궁금한 내용을 적어주시면 운영진 선생님이 댓글로 답해드려요.',
    nameLabel: '이름',
    namePlaceholder: '이름을 입력해주세요',
    contentLabel: '질문 내용',
    contentPlaceholder: '궁금한 점을 자유롭게 적어주세요',
    submit: '질문 남기기',
    submitting: '등록하는 중...',
    successToastTitle: '질문이 등록되었어요',
    successToastDescription: '운영진 선생님이 곧 답변을 남겨드릴게요.',
    errorInline: '질문 등록에 실패했어요. 잠시 후 다시 시도해주세요.',
    validation: {
      author: '이름을 입력해주세요.',
      content: '질문 내용을 입력해주세요.',
    },
  },
}
